# Creating Metrics in Numpy

In [1]:
import numpy as np

In [2]:
#create a 2x3 matrix

# Define a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Print the matrix
print(matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
# create a big matrix

b = np.arange(0,100,2).reshape(10,5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [4]:
b[4]

array([40, 42, 44, 46, 48])

In [7]:
# slicing a  matrix

c = b[1:3 , 3:5]
c

array([[16, 18],
       [26, 28]])

In [11]:
print(b.max())

print(b.min())

print(b.sum())

98
0
2450


In [12]:
# for columns only
print(b.max(axis=0))

print(b.min(axis=0))

[90 92 94 96 98]
[0 2 4 6 8]


In [13]:
# for rows only
print(b.max(axis=1))

print(b.min(axis=1))

[ 8 18 28 38 48 58 68 78 88 98]
[ 0 10 20 30 40 50 60 70 80 90]


In [17]:
#adding in existing matrix

# we can also perform other arithmatic operations

b + np.array([10,12,11,14,15])

array([[ 10,  14,  15,  20,  23],
       [ 20,  24,  25,  30,  33],
       [ 30,  34,  35,  40,  43],
       [ 40,  44,  45,  50,  53],
       [ 50,  54,  55,  60,  63],
       [ 60,  64,  65,  70,  73],
       [ 70,  74,  75,  80,  83],
       [ 80,  84,  85,  90,  93],
       [ 90,  94,  95, 100, 103],
       [100, 104, 105, 110, 113]])

In [16]:
#to add values in matrix

np.vstack((b, np.array([10,12,11,14,15])))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98],
       [10, 12, 11, 14, 15]])

In [18]:
# reversing a matrix

np.flip(b)

array([[98, 96, 94, 92, 90],
       [88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70],
       [68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50],
       [48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30],
       [28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10],
       [ 8,  6,  4,  2,  0]])