# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
#creating an array

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
#first digit
a[0]

1

In [4]:
#last digit
a[-1]

6

In [5]:
#to select muliple index

a[1:3]

array([2, 3])

In [6]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [7]:
b[2]

4

In [8]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [9]:
c[0]

array([0, 2, 4])

---
---

# DAY - 31

## Creating arrays from existing data or arrays

In [10]:
arr = np.arange(0,222,5)
arr

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [11]:
len(arr)

45

In [12]:
#creating another array from this array

arr2 = arr[30:45]
arr2

array([150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210,
       215, 220])

In [13]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

In [14]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])