In [1]:
import numpy as np

In [3]:
empty = np.empty((2,3))
empty

array([[9.34577196e-307, 9.34598246e-307, 1.60218491e-306],
       [1.69119873e-306, 1.24611673e-306, 1.05699581e-307]])

In [4]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [5]:
even = np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [8]:
even = np.arange(1,23,2)
even

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [15]:
#linear trend

lin = np.linspace(0, 10, num = 5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

what is the difference between int64,32,128 and 256,8 or float
 

In [18]:
#sorting an array

a  = np.array([1,3,6,7,3,8,10])
print(a)

[ 1  3  6  7  3  8 10]


In [19]:
a = np.sort(a)
a

array([ 1,  3,  3,  6,  7,  8, 10])

In [21]:
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,0])

c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 5, 6, 7, 8, 9, 0])

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [23]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [27]:
c = np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
c = np.concatenate((a,b),axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [32]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [41]:
a = np.array([[[0, 1, 2, 3]],

              [[4, 5, 6, 7]],

             [[5 ,6 ,3, 1]]])
a.shape

(3, 1, 4)

In [42]:
b = a.reshape(6,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [5 6]
 [3 1]]


In [44]:
# indexing and slicing
data = np.array([1, 2, 3])

print(data[1])

print(data[0:2])

print(data[1:])

print(data[-2:])


2
[1 2]
[2 3]
[2 3]


In [45]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [46]:
print(a[a < 5])


[1 2 3 4]


In [47]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [48]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [49]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [50]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [51]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
