# What is an Numpy array?

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. 
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. 

In [1]:
import numpy as np

In [11]:
# creating a 1-D numpy array

a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [10]:
# converting same array into a 2-D numpy array

b = a[np.newaxis, :]
print(b)
b.shape

[[0 1 2 3 4 5]]


(1, 6)

In [9]:
b = a[ : ,np.newaxis]
print(b)
b.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [14]:
# converting into 3-D array

c = b[np.newaxis, :]
print(c)
c.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating arrays with numpy

In [16]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6),(5,6,7,8,9,0)])

In [17]:
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [19]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [5 6 7 8 9 0]]


(2, 6)

## Initializing Arrays

In [30]:
c = np.zeros((3,5))
# print(c)
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
c = np.ones((3,5))
# print(c)
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
f = np.full((3, 5), 7)
# print(f)
f

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

## Identity matrix

In [31]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# length of an array
print(len(i))

# shape of ana array
print(i.shape)

# size of an array
print(i.size)

# dimensions of an array
print(i.ndim)


5
(5, 5)
25
2


## Performing mathematical operations on array

In [58]:
sum = a+b
print(sum)

print('\nAnother method of adding\n')

sum = np.add(a,b)
print(sum)

[[ 2  6 12 20 30 42]
 [ 2  6 12 20 30 42]]

Another method of adding

[[ 2  6 12 20 30 42]
 [ 2  6 12 20 30 42]]


In [59]:
sub = a-b
print(sub)

print('\nAnother method of subtract\n')

sub = np.subtract(a,b)
print(sub)

[[  0  -2  -6 -12 -20 -30]
 [  0  -2  -6 -12 -20 -30]]

Another method of subtract

[[  0  -2  -6 -12 -20 -30]
 [  0  -2  -6 -12 -20 -30]]


In [60]:
mul = a*b
print(mul)

print('\nAnother method of multiply\n')

mul = np.multiply(a,b)
print(mul)

[[  1   8  27  64 125 216]
 [  1   8  27  64 125 216]]

Another method of multiply

[[  1   8  27  64 125 216]
 [  1   8  27  64 125 216]]


In [57]:
sq = a**2
print(sq)

print('\nAnother method of square\n')

sq = np.square(a)
print(sq)

[ 1  4  9 16 25 36]

Another method of square

[ 1  4  9 16 25 36]
